## Concatenating Data

In [1]:
import pandas as pd
import os
from langdetect import detect
pd.set_option("display.max_colwidth", 140) # to set the column width of the table output

In [2]:
tw1 = pd.read_csv("./data/tweet-01.csv")
tw2 = pd.read_csv("./data/tweet-02.csv")
tw3 = pd.read_csv("./data/tweet-03.csv")
tw4 = pd.read_csv("./data/tweet-04.csv")
tw5 = pd.read_csv("./data/tweet-05.csv")
tw6 = pd.read_csv("./data/tweet-06.csv")
tw7 = pd.read_csv("./data/tweet-07.csv")
tw8 = pd.read_csv("./data/tweet-08.csv")

tw9_1 = pd.read_csv("./data/tweet-09-05-01.csv")
tw9_2 = pd.read_csv("./data/tweet-09-07-04.csv")
tw9_3 = pd.read_csv("./data/tweet-09-10-06.csv")
tw9_4 = pd.read_csv("./data/tweet-09-30-09.csv")

tw9 = pd.concat([tw9_1, tw9_2, tw9_3, tw9_4])

tw10 = pd.read_csv("./data/tweet-10.csv")
tw11 = pd.read_csv("./data/tweet-11.csv")
tw12 = pd.read_csv("./data/tweet-12.csv")

tw10_11 = pd.concat([tw10, tw11])
tw10_11 = tw10_11.drop_duplicates()
# tw10_11[tw10_11.duplicated(keep=False)].sort_values('id')
tw10_12 = pd.concat([tw10_11, tw12])
tw10_12 = tw10_12.drop_duplicates()
# tw10_12[tw10_12.duplicated(keep=False)].sort_values('id')
tw9 = tw9.drop_duplicates()
# tw9[tw9.duplicated(keep=False)].sort_values('id')
tw9_12 = pd.concat([tw9, tw10_12])
tw9_12 = tw9_12.drop_duplicates()
tw9_12[tw9_12.duplicated(keep=False)].sort_values('id')

Empty DataFrame
Columns: [id, name, username, date, reply_to, content, reply, retweet, like]
Index: []

In [3]:
df = pd.concat([tw1, tw2, tw3, tw4, tw5, tw6, tw7, tw8, tw9_12])
df = df.drop_duplicates()
df[df.duplicated(keep=False)].sort_values('id')

Empty DataFrame
Columns: [id, name, username, date, reply_to, content, reply, retweet, like]
Index: []

In [4]:
df = df.reset_index()
df.shape

(13958, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13958 entries, 0 to 13957
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     13958 non-null  int64
 1   id        13958 non-null  object
 2   name      13883 non-null  object
 3   username  13852 non-null  object
 4   date      13957 non-null  object
 5   reply_to  7257 non-null   object
 6   content   13957 non-null  object
 7   reply     5569 non-null   float64
 8   retweet   3196 non-null   object
 9   like      5826 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.1+ MB

In [6]:
df.describe()

              index        reply
count  13958.000000  5569.000000
mean     640.459235     3.160532
std      532.486864    14.381742
min        0.000000     1.000000
25%      233.000000     1.000000
50%      472.000000     1.000000
75%      916.000000     2.000000
max     2446.000000   396.000000

## Cleaning

### name

In [7]:
pd.set_option("display.max_colwidth", 140) # to set the column width of the table output
df[['name', 'username', 'content']][df.name.isna()].head(20)

,name,username,content
148,NaN,@terketahui,"tapi..salut dah sm org kristen/katholik..ada yang beda gini yg sesat mereka diem aja, maksudnya cukup kasih tau. coba islam wkwk syiah a..."
168,NaN,@pite_ishak,"ahmadiyah tolol, Nabi Isa AS di turun, nyet. bukan dilahir saat balik ke dunia. Si Ghulam tolol itu cm ngaku2, yg beginian lu percaya wk..."
308,NaN,@oposananonim,Wuuiiihh ayat perang pd masa nabi berjihad mau di cap kan sbgai dalil nya HRS...asbabun Nuzul nya sdh pernah di pelajari kah..???..soal ...
369,NaN,@milliongs,"indonesia is not actually lgbt friendly but trust me they persecuted more antek pki, ahmadiyah, dan kafir than gays"
1428,NaN,@alfiarnimakhtaf,"Indonesia lulus jadi negara demokrasi, toleran dan dewasa dlm beragama kalau masjid2 kaum syiah dan ahmadiyah sudah dibuka. Temlen udah ..."
1540,NaN,@alfiarnimakhtaf,"Faktanya belum terjadi begitu. Masih normatif. Muslim syiah, ahmadiyah samsek blm menikmati kebebasan. Bahkan sy perhatikan justeru se..."
1637,NaN,@josephbachsin,"Maka sebagai sesama saudara muslim dan muslimah, menghentikan pemikiran dan tindakan sesat seperti ini adalah tanggung jawab kita sebaga..."
1748,NaN,@ferr9ro,"Ahmadiyah movement moving bare brave these days, they'll know about when the real Messiah comes"
1817,NaN,@_butet_harahap,"Perang saudara Ambon, terjadi di jaman Habibie, mbak. Bertahun-tahun karena \n@DivHumas_Polri\n dan \n@Puspen_TNI\n ikut bertikai.\n\nPe..."
1855,NaN,@kurootsukkl,gw ahmadiyah lu jangan pitnah
1955,NaN,@iyasss___,"MuAh Mu, Ahmadiyah."
2386,NaN,@Abu_Hafiiz,Ya kalo udah ngaku punya nabi stlh Rasulullah udah jelas sesatny....\n\nKalo syiah kan taqiyah trs...ngaku Islam tp mncela banyak sahaba...
2517,NaN,@radowelt,btw ngebuzzer di israel ada orang islam arab sih biasa banget. tau ga di israel ada kota haifa pusatnya komunitas ahmadiyah & agama baha...
3270,NaN,@solechan_talk,"Masalahnya om, ahmadiyah itu bukan agama sendiri dan diakui pemerintah, tp mengaku islam dengan ajaran yg tidak sesuai Quran dan hadists..."
3271,NaN,@solechan_talk,"Dari dulu ga ada yg bisa nangkap poin ini, tp selalu menonjolkan prulalisme, kecuali kalo ahmadiyah declare sbg agama sendiri dan diakui..."
3448,NaN,@alfiarnimakhtaf,"Jangan ngarep palestina bisa bebas dari penjajahan, selama umat muslim masih mengkafirkan kaum syiah dan ahmadiyah seenak bacotnya, dan..."
3451,NaN,@alfiarnimakhtaf,"Kaga usah sok2an musingin palestina, yg deket2 aja dulu tengok; muslim syiah dan ahmadiyah yang dikafirkan, hidup dipengungsian di nega..."
4050,NaN,@prplee3to3,Astaghfirullah baru tau yg Ahmadiyah
4298,NaN,@HirmanF,"Mau nanya .\nJiL,syiah ,Ahmadiyah mana yg paling melenceng ?"
4361,NaN,@roysamudro,Suneo Rachel Ciuman Olin Zara #SedekatSahabat \n32 GB Jonatan Christie Ginting Rans Indosiar Ngilu The Daddies Ahmadiyah Ridho Ginting M...

### username

In [8]:
df[['name', 'username', 'content']][df.username.isna()].head(20)

,name,username,content
1164,RAKYAT BERSATU MELAWAN KOMUNIS IMPERIALIS,NaN,"2005 2008 ketika ahmadiyah jadi wayang , dia ada bersamaan."
1511,Anti Feodalism Aparteid Unfairness Racism Ibn Xine,NaN,"Ya benar saya selalu tertarik dan belajar Syiah, LDII, Ahmadiyah kalau tidak, tidak tahu mereka. Apalagi Islam liberal. Lebih merusak la..."
1552,Anti Feodalism Aparteid Unfairness Racism Ibn Xine,NaN,"Jadi yang direkrut untuk melawan umat Islam dan memusnahkan ajaran Islam itu JIL, Syiah, LDII, Ahmadiyah, semua dengan jelas diketahui u..."
1629,Agama Kepercayaan Adat Nusantara (GBMYLKSKVXYWQ),NaN,"(KTP).\n\nKiai asal Tasikmalaya, Jawa Barat ini ini mencontohkan JAI (Jemaah Ahmadiyah Indonesia) yang kebetulan banyak penganutnya di K..."
1874,Buzzer NKRI HABBUL WATHON MINAL IMAN,NaN,Munarman woii Ahmadiyah pihak yg terzolimi loe bela tidak?
2091,Gerombolan BAJINGAN Tengik...,NaN,Macam hapal aja ente sama Alfateha...sok2an doain aliran sesat Ahmadiyah...
2497,Anaknya Odin garis gak lucu,NaN,Yang lebih parah kondisinya Ahmadiyah. Mereka disuruh bikin agama sendiri
2498,DANTALION DUSKY PRAYER LETTER,NaN,"Ya beda nasib dgn nabi ahmadiyah dibuatkan sanctuary & dakwahnya difasilitasi inggris, syiah akidahnya sesat tapi gak ada yg tertarik bu..."
2501,Agama Kepercayaan Adat Nusantara (GBMYLKSKVXYWQ),NaN,"Belum lagi yang syiah & ahmadiyah yang dianggap bukan islam , belum lagi juga para penghayat kepercayaan pada mau ganti status islam di ..."
2502,Anaknya Odin garis gak lucu,NaN,"Sunni : Syiah bukan Islam\nSyiah : Sunni bukan Islam\nSunni&Syiah : Ahmadiyah bikin agama sendiri saja, jangan nempel Islam\nSalafi : Sy..."
2505,Anaknya Odin garis gak lucu,NaN,"Kata kadrun, ""saudara muslim itu bagai satu tubuh,"" prett. Buktinya masih persekusi Ahmadiyah. Padahal Tuhannya sama, nabinya juga sama,..."
2520,Aphrodite Celestamine Prune,NaN,"kl yg belum punya agama.silahkam eksplorasi apa mau islam, kristen, budha, hindu, syiah atau ahmadiyah atau apa terserah dan gak usah di..."
2522,Aphrodite Celestamine Prune,NaN,"intinya org gak akan bersepakat di hal2 yy gak bener ,logika dan akal sehatnya demikian. org udah punya pilihan agama dipaksa pindsh ke ..."
2689,Aphrodite Celestamine Prune,NaN,"ada koruptor, sipilis, islamohobia, kristenisasi, pki, syiah, ahmadiyah, kebodohan, asusila, amoral ibarat tubuh banyak oenyakit penyert..."
2694,Kertaradjasa Jayawardhana,NaN,Silakan minta legitimasi kepada MUI. Dan buat pernyataan kalau Ahmadiyah tidak sesat.
2727,Kertaradjasa Jayawardhana,NaN,Ahmadiyah sama saja dengan Syiah. Sama-sama taqiyah dan ngeyel.
2740,Ujeng yg bangga dg 75 follower,NaN,"Satu pertanyaan lagi, kenapa Khalifah Ahmadiyah memakai ""Sir"" didepan namanya ?"
2741,Ujeng yg bangga dg 75 follower,NaN,"Kami hanya memiliki sikap, jika Ahmadiyah tetap mengatakan pendirinya atau siapapun sebagai Nabi Penerus/Imam Mahdi, maka Ahmadiyah bera..."
2743,Kertaradjasa Jayawardhana,NaN,"Ahmadiyah kan sesat\nAkidahnya pantas ""dihajar"""
2762,Ujeng yg bangga dg 75 follower,NaN,Islam kenapa ngaku ahmadiyah atau Islam Ahmadiyah ??\nBedanya prinsipil nya dimana ?

In [9]:
df[['name', 'username', 'content']][df.username.isna() & df.name.isna()]

Empty DataFrame
Columns: [name, username, content]
Index: []

No sample with null value in both name & username. Let's fill username with name and vice versa

In [10]:
df.name.fillna(df['username'][df.name.isna()], inplace=True)
df[['name', 'username', 'content']][df.index == 148]

,name,username,content
148,@terketahui,@terketahui,"tapi..salut dah sm org kristen/katholik..ada yang beda gini yg sesat mereka diem aja, maksudnya cukup kasih tau. coba islam wkwk syiah a..."

In [11]:
df.username.fillna(df['name'][df.username.isna()], inplace=True)
df[['name', 'username', 'content']][df.index == 1164]

,name,username,content
1164,RAKYAT BERSATU MELAWAN KOMUNIS IMPERIALIS,RAKYAT BERSATU MELAWAN KOMUNIS IMPERIALIS,"2005 2008 ketika ahmadiyah jadi wayang , dia ada bersamaan."

In [51]:
df[[nm[0] == '#' for nm in df.username]]

,index,id,name,username,date,reply_to,content,reply,retweet,like,retweet_isnumeric,like_isnumeric,lang,mentions,content_clean
2843,352,#usemaskandfaceshieldMay202021bacot.,#usemaskandfaceshield,#usemaskandfaceshield,2021-05-20,nan,"bacot. anwar abbas bilang apa ke orang2 syiah, ahmadiyah di indonesia? bunuh mereka. mereka kafir\n\nlol",0,0,0,1,1,id,,"bacot. anwar abbas bilang apa ke orang2 syiah, ahmadiyah di indonesia? bunuh mereka. mereka kafir lol"
3390,903,#IndonesiaTERSERAH2020May102021Kalo di,#IndonesiaTERSERAH2020,#IndonesiaTERSERAH2020,2021-05-10,@Bagasta8,"Kalo di London, kayanya ga kepikiran dia Ahmadiyah atau NU atau Muhammadiyah. Yang penting kapabel dg jabatan.\nBeda cerita kalo di DKI,...",1,1,2,1,1,id,,"Kalo di London, kayanya ga kepikiran dia Ahmadiyah atau NU atau Muhammadiyah. Yang penting kapabel dg jabatan. Beda cerita kalo di DKI, ..."
3757,1270,#OligarkiBiangKehancuranRIMay42021Kaum mu,#OligarkiBiangKehancuranRI,#OligarkiBiangKehancuranRI,2021-05-04,@DiaanaNama,"Kaum munafik merasa aman menista Islam&merusak akidah krn mengaku muslim. Coba kalo kolom agama di KTP mencantumkan ""keyakinan"" nya masi...",1,0,1,1,1,id,,"Kaum munafik merasa aman menista Islam&merusak akidah krn mengaku muslim. Coba kalo kolom agama di KTP mencantumkan ""keyakinan"" nya masi..."
6299,604,#JANGANtuhankanWongArabSep42021Pas kej,#JANGANtuhankanWongArab,#JANGANtuhankanWongArab,2021-09-04,nan,Pas kejadian mereka ada di depan mata. \nMalah di ajak berdebat..... Dipanggil saudaraku lagi oleh petugas di lapangan. \nKenapa tidak d...,5,12,36,1,1,id,,Pas kejadian mereka ada di depan mata. Malah di ajak berdebat..... Dipanggil saudaraku lagi oleh petugas di lapangan. Kenapa tidak di GE...
8566,751,#JANGANtuhankanWongArabSep62021Hukum s,#JANGANtuhankanWongArab,#JANGANtuhankanWongArab,2021-09-06,nan,Hukum seberat²nya..... Sejajar kan dengan hukuman pelaku teror. \n\nMereka sebenarnya sudah seperti teroris!!!! \n\n10 Pelaku Perusakan ...,2,6,14,1,1,id,,Hukum seberat²nya..... Sejajar kan dengan hukuman pelaku teror. Mereka sebenarnya sudah seperti teroris!!!! 10 Pelaku Perusakan Masjid A...
9350,1537,#JANGANtuhankanWongArabSep52021Ilmu \n@,#JANGANtuhankanWongArab,#JANGANtuhankanWongArab,2021-09-05,nan,Ilmu \n@stik_ptik\n apakah ada ajarkan Strategi itu? \n\nCc \n@DivHumas_Polri\n@Kepolisian_RI\n @Puspen_TNI\nPerusak Masjid Ahmadiyah Ta...,6,5,23,1,1,id,@stik_ptik @DivHumas_Polri @Kepolisian_RI @Puspen_TNI,"Ilmu apakah ada ajarkan Strategi itu? Cc Perusak Masjid Ahmadiyah Tak Ditangkap, Polisi Klaim Strategi"
10387,371,#JANGANtuhankanWongArabSep82021Seperti,#JANGANtuhankanWongArab,#JANGANtuhankanWongArab,2021-09-08,nan,Seperti halnya kasus yahya waloni...... Sudah ditangkap baru bersuara. \n#BubarkanMUI ..... Isinya kebanyakan BANGSAT daripada ulama.......,2,9,14,1,1,id,,Seperti halnya kasus yahya waloni...... Sudah ditangkap baru bersuara. #BubarkanMUI ..... Isinya kebanyakan BANGSAT daripada ulama.....!...

### Date

In [12]:
df[['name', 'username', 'content', 'date']][df.date.isna()]

,name,username,content,date
2813,Taylor Nieman,@Taylor_Nieman,Now you can learn a language just by reading your favorite websites.,NaN

The tweet with nan value in date is an advertisement. Let's drop it

In [13]:
df.dropna(subset='date', inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13957 entries, 0 to 13957
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     13957 non-null  int64
 1   id        13957 non-null  object
 2   name      13957 non-null  object
 3   username  13957 non-null  object
 4   date      13957 non-null  object
 5   reply_to  7257 non-null   object
 6   content   13956 non-null  object
 7   reply     5568 non-null   float64
 8   retweet   3195 non-null   object
 9   like      5825 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.2+ MB

In [15]:
print(df['date'][df.date == 'Aug 2, 2021'])
def convert_date(text: str):
    month_dict = {
        'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04',
        'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08',
        'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }
    bulan = text.split(' ')[0]
    bulan = month_dict[bulan]
    tahun = text.split(' ')[-1]
    tanggal = text.split(',')[0].split(' ')[-1]
    tanggal = tanggal if len(tanggal) == 2 else ('0' + tanggal)
    return f'{tahun}-{bulan}-{tanggal}'

5659    Aug 2, 2021
5660    Aug 2, 2021
5661    Aug 2, 2021
5662    Aug 2, 2021
5663    Aug 2, 2021
5664    Aug 2, 2021
5665    Aug 2, 2021
5666    Aug 2, 2021
5667    Aug 2, 2021
5668    Aug 2, 2021
5669    Aug 2, 2021
5670    Aug 2, 2021
5671    Aug 2, 2021
5672    Aug 2, 2021
5673    Aug 2, 2021
5674    Aug 2, 2021
5675    Aug 2, 2021
5676    Aug 2, 2021
5677    Aug 2, 2021
5678    Aug 2, 2021
Name: date, dtype: object

In [16]:
df.date = df.date.apply(convert_date)
df.date = pd.to_datetime(df.date)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13957 entries, 0 to 13957
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     13957 non-null  int64
 1   id        13957 non-null  object
 2   name      13957 non-null  object
 3   username  13957 non-null  object
 4   date      13957 non-null  datetime64[ns]
 5   reply_to  7257 non-null   object
 6   content   13956 non-null  object
 7   reply     5568 non-null   float64
 8   retweet   3195 non-null   object
 9   like      5825 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 1.2+ MB

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13957 entries, 0 to 13957
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     13957 non-null  int64
 1   id        13957 non-null  object
 2   name      13957 non-null  object
 3   username  13957 non-null  object
 4   date      13957 non-null  datetime64[ns]
 5   reply_to  7257 non-null   object
 6   content   13956 non-null  object
 7   reply     5568 non-null   float64
 8   retweet   3195 non-null   object
 9   like      5825 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 1.2+ MB

### reply_to

In [18]:
df[['name', 'username', 'content', 'reply_to']][df.reply_to.isna()]

,name,username,content,reply_to
0,Deden Sujana,@dedensujana,Simak bagaimana sikap Khilafah Ahmadiyah terhadap Pancasila dan Demokrasi dalam link di bawah ini :\n@Iskandargumay1,NaN
5,Fuad Ahmad Nasir,@fuadahmad88,Pengajian Mingguan Online\n\nTajuk: Tahrik Waqf-e-Nau\n\nDibawakan oleh: \nDepartment Tarbiyat Nasional\nJamaat Ahmadiyah Mulsim Malaysia,NaN
7,dont cry,@_mediocry,"banyak juga yaa. ini kalo di islam semacam nu, muhammadiyah, ahbandiyah, ahmadiyah, ldii dsb gitu gak sih?",NaN
9,Robby Satya Andhika,@robbysa,Kalau Ahmadiyah dan Syiah bagaimana?,NaN
10,Iman Mubarak Ahmad,@imanmubarak_a,Kunjungan Intel Kodim 0703 ke Rumah Mubaligh Ahmadiyah Cilacap\n\nhttps://ayahakbar.id/2021/01/31/kunjungan-intel-kodim-0703-ke-rumah-mu...,NaN
...,...,...,...,...
13949,Deden Sujana,@dedensujana,"Official Trailer : ""TITIK TERANG AHMADIYAH"".\n\nVideo dokumenter ini menceritakan kisah tentang para tokoh Dayak Kalimantan Barat yang m...",NaN
13951,Septian,@Septianaji_20,"Walaupun dekat dengan Sekte Ahmadiyah,\ntidak pernah sekalipun membenarkan Sekte nya.\nSama-sama dalam Sosial",NaN
13952,bill temporo,@BillTemporo,GAFATAR=Gerakan Fajar Nusantara=AHMADIYAH=KAFIR,NaN
13953,Beritabaru.co,@Beritabaruco,FBTI Tasikmalaya Gelar Kemah Toleransi Demi Membuka Ruang Diskusi http://dlvr.it/SDWzSp #Ahmadiyah #forumbhinnekatunggalika #kemahtoleransi,NaN
13956,Ekajuwa,@ekajuwa,"#IslamMempersatukanKita Kata Siapa? Rosul sendiri menyatakan Islam akan terpecah mjd berapa bagian. Itu terbukti dgn adanya Sunni, Syiah...",NaN

In [19]:
df.reply_to = df.reply_to.astype(str)

### content

In [20]:
df[['name', 'username', 'content', 'reply_to']][df.content.isna()]

                name          username content          reply_to
2428  insanduniafana  @_insanduniafana     NaN  @tambaljam24ban_

In [21]:
df.dropna(subset='content', inplace=True)

In [22]:
df[['name', 'username', 'content', 'reply_to']][df.content.isna()]

Empty DataFrame
Columns: [name, username, content, reply_to]
Index: []

### reply
Number of replies

In [23]:
df[['name', 'username', 'content', 'reply']][df.reply.isna()].head()

,name,username,content,reply
0,Deden Sujana,@dedensujana,Simak bagaimana sikap Khilafah Ahmadiyah terhadap Pancasila dan Demokrasi dalam link di bawah ini :\n@Iskandargumay1,NaN
2,risris isman,@risrisus,"Sebenarnya mengomentari \n@permadiaktivis1\n lebih politis dari pada bicara HAM, mana berani para politikus menaggapi apalagi bersuara l...",NaN
3,MuridIslamAhmadiyah,@MAhmadiyah,adakah pernyataan dari Ahmadiyah bahwa nabi penutup adalah Bukan Muhammad melainkan Mirza Ghulam Ahmad? silahkan tunjukan disini,NaN
5,Fuad Ahmad Nasir,@fuadahmad88,Pengajian Mingguan Online\n\nTajuk: Tahrik Waqf-e-Nau\n\nDibawakan oleh: \nDepartment Tarbiyat Nasional\nJamaat Ahmadiyah Mulsim Malaysia,NaN
7,dont cry,@_mediocry,"banyak juga yaa. ini kalo di islam semacam nu, muhammadiyah, ahbandiyah, ahmadiyah, ldii dsb gitu gak sih?",NaN

In [24]:
df.reply.fillna(0, inplace=True)
df.reply = df.reply.astype(int)
df[['name', 'username', 'content', 'reply']][df.reply == 0].head()

,name,username,content,reply
0,Deden Sujana,@dedensujana,Simak bagaimana sikap Khilafah Ahmadiyah terhadap Pancasila dan Demokrasi dalam link di bawah ini :\n@Iskandargumay1,0
2,risris isman,@risrisus,"Sebenarnya mengomentari \n@permadiaktivis1\n lebih politis dari pada bicara HAM, mana berani para politikus menaggapi apalagi bersuara l...",0
3,MuridIslamAhmadiyah,@MAhmadiyah,adakah pernyataan dari Ahmadiyah bahwa nabi penutup adalah Bukan Muhammad melainkan Mirza Ghulam Ahmad? silahkan tunjukan disini,0
5,Fuad Ahmad Nasir,@fuadahmad88,Pengajian Mingguan Online\n\nTajuk: Tahrik Waqf-e-Nau\n\nDibawakan oleh: \nDepartment Tarbiyat Nasional\nJamaat Ahmadiyah Mulsim Malaysia,0
7,dont cry,@_mediocry,"banyak juga yaa. ini kalo di islam semacam nu, muhammadiyah, ahbandiyah, ahmadiyah, ldii dsb gitu gak sih?",0

### retweet
Number of retweets

In [25]:
df[['name', 'username', 'content', 'retweet']].sample(5, random_state=1)

,name,username,content,retweet
825,Xavier919,@avatarcs999,Jadi ini semua anggota Ahmadiyah salah paham??? Ancaman itu cuma main-main saja? Ngk serius maksud lu???\n\nhttps://news.detik.com/berit...,NaN
6837,Supardi,@mbahdoro1,"Kenapa namanya masjid Ahmadiyah, terus apa bedanya dengan masjid masjid yang sudah ini .\nSerius nanya",NaN
10642,Indra Baso,@NusantaraNol,Tolong sampaikan ke Ahmadiyah,NaN
11666,Pusat Berita Islam,@PBIslam,"Empat Ormas Islam Keluarkan Penyataan, Ajak Ahmadiyah Kembali pada Islam yang Benar",NaN
8955,Tukang Rosok,@tukangrosok___,Dlm sejarah berdirinya NKRI belum pernah Jama'ah Ahmadiyah mengusik ketenangan sesama warga Negara Indonesia.\nMelainkan Ikut berjuang d...,67.0

In [26]:
def isthisnumeric(val):
    val = str(val)
    val = val.replace('.', '')
    if val.isnumeric():
        return 1
    else:
        return 0

df.retweet.fillna(0, inplace=True)
df['retweet_isnumeric'] = df.retweet.apply(lambda x: isthisnumeric(x))
df[['username', 'content', 'retweet', 'retweet_isnumeric']][df.retweet_isnumeric == 0]

,username,content,retweet,retweet_isnumeric
4943,@malakmalakmal,"Dalam bukunya, ""Pelajaran Agama Islam"", Buya Hamka sudah menjelaskan dua aliran sesat, yaitu Ahmadiyah dan Baha'iyah.",1.7K,0
7775,@AlissaWahid,"Sekelompok orang mengatasnamakan umat Islam merusak bangunan masjid Ahmadiyah di Sintang. Apapun alasannya, ini tindakan melanggar hukum...",1.2K,0

In [27]:
df = df.copy()
df['retweet'][df.retweet_isnumeric == 0] = df['retweet'][df.retweet_isnumeric == 0].apply(lambda x: x.replace('.', '').replace('K', '00'))
df[['username', 'content', 'retweet', 'retweet_isnumeric']][df.retweet_isnumeric == 0]

<ipython-input-27-277fedd9cb6d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['retweet'][df.retweet_isnumeric == 0] = df['retweet'][df.retweet_isnumeric == 0].apply(lambda x: x.replace('.', '').replace('K', '00'))

,username,content,retweet,retweet_isnumeric
4943,@malakmalakmal,"Dalam bukunya, ""Pelajaran Agama Islam"", Buya Hamka sudah menjelaskan dua aliran sesat, yaitu Ahmadiyah dan Baha'iyah.",1700,0
7775,@AlissaWahid,"Sekelompok orang mengatasnamakan umat Islam merusak bangunan masjid Ahmadiyah di Sintang. Apapun alasannya, ini tindakan melanggar hukum...",1200,0

In [28]:
df.retweet = df.retweet.astype(int)
df[['name', 'username', 'content', 'retweet']].sample(5, random_state=1)

,name,username,content,retweet
825,Xavier919,@avatarcs999,Jadi ini semua anggota Ahmadiyah salah paham??? Ancaman itu cuma main-main saja? Ngk serius maksud lu???\n\nhttps://news.detik.com/berit...,0
6837,Supardi,@mbahdoro1,"Kenapa namanya masjid Ahmadiyah, terus apa bedanya dengan masjid masjid yang sudah ini .\nSerius nanya",0
10642,Indra Baso,@NusantaraNol,Tolong sampaikan ke Ahmadiyah,0
11666,Pusat Berita Islam,@PBIslam,"Empat Ormas Islam Keluarkan Penyataan, Ajak Ahmadiyah Kembali pada Islam yang Benar",0
8955,Tukang Rosok,@tukangrosok___,Dlm sejarah berdirinya NKRI belum pernah Jama'ah Ahmadiyah mengusik ketenangan sesama warga Negara Indonesia.\nMelainkan Ikut berjuang d...,67

### like
Number of likes

In [29]:
df[['name', 'username', 'content', 'like']].sample(5, random_state=1)

,name,username,content,like
825,Xavier919,@avatarcs999,Jadi ini semua anggota Ahmadiyah salah paham??? Ancaman itu cuma main-main saja? Ngk serius maksud lu???\n\nhttps://news.detik.com/berit...,NaN
6837,Supardi,@mbahdoro1,"Kenapa namanya masjid Ahmadiyah, terus apa bedanya dengan masjid masjid yang sudah ini .\nSerius nanya",2
10642,Indra Baso,@NusantaraNol,Tolong sampaikan ke Ahmadiyah,NaN
11666,Pusat Berita Islam,@PBIslam,"Empat Ormas Islam Keluarkan Penyataan, Ajak Ahmadiyah Kembali pada Islam yang Benar",NaN
8955,Tukang Rosok,@tukangrosok___,Dlm sejarah berdirinya NKRI belum pernah Jama'ah Ahmadiyah mengusik ketenangan sesama warga Negara Indonesia.\nMelainkan Ikut berjuang d...,146

In [30]:
df.like.fillna(0, inplace=True)
df['like_isnumeric'] = df.like.apply(lambda x: isthisnumeric(x))
df[['username', 'content', 'like', 'like_isnumeric']][df.like_isnumeric == 0]

,username,content,like,like_isnumeric
259,@IrutPagut,"FOTO RAFI AHMAD DAN KAKEKNYA ""MALIK AZIS AHMAD KHAN"" ASAL PAKISTAN.\nBanyak yang belum Tau kalau Rafi Ahmad Cucu dari Penyebar Aliran Se...",1.6K,0
1939,@Barack_AM,Dulu Istiqlal dibangun dgn dana gotong royong seluruh rakyat Indonesia tanpa melihat latarnya. Sumbangan berasal dari berbagai macam kal...,1.3K,0
2181,@_ekokuntadhi,"Gak heran, kan. Di era SBY, HTI siaran langsung di TVRI kampanye khilafah dan menistai Pancasila? \n\nGak heran, pengikut Ahmadiyah dibu...",1K,0
3132,Ulil Abshar-Abdalla #SudahVaksin,"Temen2 yg selama ini bersemangat membela kaum minoritas di Indonesia, seperti Ahmadiyah dan Syiah, akan lebih konsisten jika bersikap te...",1.8K,0
3327,@AlissaWahid,"Minggu terakhir Ramadan ini penuh tantangan kebangsaan. Hak kelp minoritas soal seragam sekolah, hubungan Pusat Daerah yg makin tumpang-...",1.7K,0
4536,@NurazizaShima,"""Kesalahan terburuk kita adalah ketertarikan kita pada kesalahan orang lain."" -Ali bin Abi Thalib- \n\nMaljum, Malam Jumat, Joko\nAhmadi...",1K,0
4943,@malakmalakmal,"Dalam bukunya, ""Pelajaran Agama Islam"", Buya Hamka sudah menjelaskan dua aliran sesat, yaitu Ahmadiyah dan Baha'iyah.",4.1K,0
7668,@saidiman,Ini bangunan warga Ahmadiyah Sintang. Dirusak para begundal di hadapan aparat tak tahu malu. Pakaian lengkap siap tempur. Jumlahnya bany...,1.5K,0
7774,@AlissaWahid,"Syariat siapa yang mengajarkan boleh merusak bangunan orang lain, main hakim sendiri, meneror? \n\nAnda boleh tidak setuju keyakinan ora...",1K,0
7775,@AlissaWahid,"Sekelompok orang mengatasnamakan umat Islam merusak bangunan masjid Ahmadiyah di Sintang. Apapun alasannya, ini tindakan melanggar hukum...",2.5K,0
8177,@emerson_yuntho,Assalamualaikum Wr Wb Pak \n@hnurwahid\n jika dibutuhkan saya bisa bantu buatkan draft pernyataan Bapak tentang kecaman perusakan rumah ...,1.4K,0
8634,@_ekokuntadhi,Jika masjid Ahmadiyah dibakar gerombolan cingkrang. Tp umat Islam diam saja. Malah agama lain yang ikut geram. \n\nTandanya kita sebagai...,1.3K,0
8939,@_ekokuntadhi,"Perhatikan gerombolan perusak masjid Ahmadiyah di Sintang : daster, celana cingkrang, jenggot. Sebagian jidat item. \n\nDimana ada gerom...",2.2K,0
9190,@sahaL_AS,MUI-Muhammadiyah-NU sama2 mengecam perusakan masjid Ahmadiyah di Kalbar,1K,0
10856,@AgoesAguss,"Si kutil PAJERO provokator pembakaran mesjid ahmadiyah sudah ditangkap guys,..",1.5K,0
10873,@emerson_yuntho,Assalamualaikum Wr Wb Pak \n@hnurwahid\n jika dibutuhkan saya bisa bantu buatkan draft pernyataan Bapak tentang kecaman perusakan rumah ...,1.4K,0
12678,@TaufikDamas,"Anda boleh tidak setuju pada paham Ahmadiyah. Saya pun begitu. Tapi, menyegel tempat ibadahnya adalah tindakan biadab.",1.2K,0

In [31]:
df['like'][df.like_isnumeric == 0] = df['like'][df.like_isnumeric == 0].apply(lambda x: x.replace('.', '').replace('K', '00'))
df[['username', 'content', 'like', 'like_isnumeric']][df.like_isnumeric == 0]

<ipython-input-31-9b96cf76b976>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['like'][df.like_isnumeric == 0] = df['like'][df.like_isnumeric == 0].apply(lambda x: x.replace('.', '').replace('K', '00'))

,username,content,like,like_isnumeric
259,@IrutPagut,"FOTO RAFI AHMAD DAN KAKEKNYA ""MALIK AZIS AHMAD KHAN"" ASAL PAKISTAN.\nBanyak yang belum Tau kalau Rafi Ahmad Cucu dari Penyebar Aliran Se...",1600,0
1939,@Barack_AM,Dulu Istiqlal dibangun dgn dana gotong royong seluruh rakyat Indonesia tanpa melihat latarnya. Sumbangan berasal dari berbagai macam kal...,1300,0
2181,@_ekokuntadhi,"Gak heran, kan. Di era SBY, HTI siaran langsung di TVRI kampanye khilafah dan menistai Pancasila? \n\nGak heran, pengikut Ahmadiyah dibu...",100,0
3132,Ulil Abshar-Abdalla #SudahVaksin,"Temen2 yg selama ini bersemangat membela kaum minoritas di Indonesia, seperti Ahmadiyah dan Syiah, akan lebih konsisten jika bersikap te...",1800,0
3327,@AlissaWahid,"Minggu terakhir Ramadan ini penuh tantangan kebangsaan. Hak kelp minoritas soal seragam sekolah, hubungan Pusat Daerah yg makin tumpang-...",1700,0
4536,@NurazizaShima,"""Kesalahan terburuk kita adalah ketertarikan kita pada kesalahan orang lain."" -Ali bin Abi Thalib- \n\nMaljum, Malam Jumat, Joko\nAhmadi...",100,0
4943,@malakmalakmal,"Dalam bukunya, ""Pelajaran Agama Islam"", Buya Hamka sudah menjelaskan dua aliran sesat, yaitu Ahmadiyah dan Baha'iyah.",4100,0
7668,@saidiman,Ini bangunan warga Ahmadiyah Sintang. Dirusak para begundal di hadapan aparat tak tahu malu. Pakaian lengkap siap tempur. Jumlahnya bany...,1500,0
7774,@AlissaWahid,"Syariat siapa yang mengajarkan boleh merusak bangunan orang lain, main hakim sendiri, meneror? \n\nAnda boleh tidak setuju keyakinan ora...",100,0
7775,@AlissaWahid,"Sekelompok orang mengatasnamakan umat Islam merusak bangunan masjid Ahmadiyah di Sintang. Apapun alasannya, ini tindakan melanggar hukum...",2500,0
8177,@emerson_yuntho,Assalamualaikum Wr Wb Pak \n@hnurwahid\n jika dibutuhkan saya bisa bantu buatkan draft pernyataan Bapak tentang kecaman perusakan rumah ...,1400,0
8634,@_ekokuntadhi,Jika masjid Ahmadiyah dibakar gerombolan cingkrang. Tp umat Islam diam saja. Malah agama lain yang ikut geram. \n\nTandanya kita sebagai...,1300,0
8939,@_ekokuntadhi,"Perhatikan gerombolan perusak masjid Ahmadiyah di Sintang : daster, celana cingkrang, jenggot. Sebagian jidat item. \n\nDimana ada gerom...",2200,0
9190,@sahaL_AS,MUI-Muhammadiyah-NU sama2 mengecam perusakan masjid Ahmadiyah di Kalbar,100,0
10856,@AgoesAguss,"Si kutil PAJERO provokator pembakaran mesjid ahmadiyah sudah ditangkap guys,..",1500,0
10873,@emerson_yuntho,Assalamualaikum Wr Wb Pak \n@hnurwahid\n jika dibutuhkan saya bisa bantu buatkan draft pernyataan Bapak tentang kecaman perusakan rumah ...,1400,0
12678,@TaufikDamas,"Anda boleh tidak setuju pada paham Ahmadiyah. Saya pun begitu. Tapi, menyegel tempat ibadahnya adalah tindakan biadab.",1200,0

In [32]:
df.like = df.like.astype(int)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13956 entries, 0 to 13957
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              13956 non-null  int64
 1   id                 13956 non-null  object
 2   name               13956 non-null  object
 3   username           13956 non-null  object
 4   date               13956 non-null  datetime64[ns]
 5   reply_to           13956 non-null  object
 6   content            13956 non-null  object
 7   reply              13956 non-null  int32
 8   retweet            13956 non-null  int32
 9   like               13956 non-null  int32
 10  retweet_isnumeric  13956 non-null  int64
 11  like_isnumeric     13956 non-null  int64
dtypes: datetime64[ns](1), int32(3), int64(3), object(5)
memory usage: 1.7+ MB

### language

In [34]:
df['lang'] = df.content.apply(lambda x: detect(x))

In [35]:
df['lang'].value_counts()

id    12976
so      561
en      335
tl       31
de       22
sw        9
no        4
et        3
fr        3
tr        2
ca        2
ur        2
sl        2
pt        1
vi        1
af        1
sv        1
Name: lang, dtype: int64

In [36]:
lang_to_drop = ['en', 'et', 'fr', 'no', 'ur', 'sl', 'sv']

In [37]:
df[['content', 'lang']][df.lang == 'sv']

                                        content lang
12868  Ahmadiyah är inte muslimer staghforallah   sv

In [38]:
df = df[~df.lang.isin(lang_to_drop)]

In [39]:
df.shape

(13606, 13)

### Extract mentions

In [40]:
def extract_mentions(text):
    mentions = []
    text = text.split('\n')
    for item in text:
        for i in item.split():
            if i[0] == '@':
                mentions.append(i)
    return ' '.join(mentions)

In [41]:
df['mentions'] = df.content.apply(extract_mentions)
df[['content', 'mentions']][df.mentions != '']

,content,mentions
0,Simak bagaimana sikap Khilafah Ahmadiyah terhadap Pancasila dan Demokrasi dalam link di bawah ini :\n@Iskandargumay1,@Iskandargumay1
2,"Sebenarnya mengomentari \n@permadiaktivis1\n lebih politis dari pada bicara HAM, mana berani para politikus menaggapi apalagi bersuara l...",@permadiaktivis1
51,"Kapan Susi membela Minoritas, Ahmadiyah, Syiah ketika dianiaya ? Tapi kalau \n@permadiaktivis1\n sudah terbukti sepak terjangnya membela...",@permadiaktivis1
56,"Kapolri sudah datang ke DPP NU dan Muhamadiyah ,Kapan bisa ketemu dgn Pengurus Besar Jemaah Ahmadiyah ? \n@DivHumas_Polri",@DivHumas_Polri
64,ahmadiyah kapan nih bs beribadah tanpa dipasung SKB..\n@YaqutCQoumas\n @dedensujana,@YaqutCQoumas @dedensujana
...,...,...
13915,IDN TIMES JATENG \n@IDNTimesJateng\nMubaligh Ahmadiyah Lawan Diskriminasi Lewat Solidaritas Umat Beragama,@IDNTimesJateng
13921,Belajar lah dengan ALIM ULAMA SOLEH dari kalangan Kyai/Gus/Habib Ahlussunnah wal Jama'ah. Jangan belajar dari Ulama Su'/Syi'ah/Ahmadiyah...,@tni_ad @IBNUHUSEINATS @ali_hasan110 @mr_banan12 @abubakarsegaf @NovalAssegaf @ustad_alhabsyi @ustsegafbaharun
13935,"PREMIERE VIDEO DOKUMENTER :""TITIK TERANG AHMADIYAH"".\n\nSebuah video dokumenter yang menyajikan informasi dan fakta objektif terkait Ahm...",@Iskandargumay1
13946,"@GUSDURians\n up, maaf. Ini bukan penolakan gereja, LDII atau Ahmadiyah.",@GUSDURians
13949,"Official Trailer : ""TITIK TERANG AHMADIYAH"".\n\nVideo dokumenter ini menceritakan kisah tentang para tokoh Dayak Kalimantan Barat yang m...",@Iskandargumay1

## content_clean

In [42]:
content_clean = []
# Removing twitter mentions and links
for _, row in df.iterrows():
    content = row['content']
    mentions = row['mentions'].split()
    for mention in mentions:
        content = content.replace(mention, '')
    content = content.replace('\n', ' ')
    content = content.split()
    for i, item in enumerate(content):
        if 'http' in item:
            content.pop(i)
    content = ' '.join(content)
    content_clean.append(content)
df['content_clean'] = content_clean

In [43]:
df.isna().sum()

index                0
id                   0
name                 0
username             0
date                 0
reply_to             0
content              0
reply                0
retweet              0
like                 0
retweet_isnumeric    0
like_isnumeric       0
lang                 0
mentions             0
content_clean        0
dtype: int64

## Export

In [44]:
df_clean = df.drop(['index', 'retweet_isnumeric', 'like_isnumeric'], axis=1)
df_clean = df_clean.reset_index(drop=True)
df_clean.to_csv('./data/tweet-clean.csv', index=False)

In [46]:
df_new = pd.read_csv('./data/tweet-clean.csv')
df_clean = df_new[~df_new.content_clean.isna()].reset_index(drop=True)
df_clean.to_csv('./data/tweet-clean.csv', index=False)
df_new = pd.read_csv('./data/tweet-clean.csv')
df_new.isna().sum()

id                   0
name                 0
username             0
date                 0
reply_to          6474
content              0
reply                0
retweet              0
like                 0
lang                 0
mentions         12301
content_clean        1
dtype: int64

## I think it's done